### ISSUE TITLE
Feature Requests : Use IAM role instead of AWS keys

### ISSUE THREAD

**Issue by Dharmender-Singh** [neillturner/puppet-aws_scheduler#1]
Hi,

Are you planing any release for support the IAM role and make the AWS keys optional. Currently these keys are compulsory.

-Dharmender

**Comment by neillturner** [comment]
ok i've coded that. if you could test by changing the librarian-puppet config to 
https://github.com/neillturner/puppet-aws_scheduler
if it works i will release new version to puppetforge

**Comment by Dharmender-Singh** [comment]
I have made the changes according to your last check in but getting following error : ----

Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file aws-scheduler.py, line 139
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file aws-scheduler.py, line 139

**Comment by neillturner** [comment]
can you show the the output of the puppet run?

**Comment by Dharmender-Singh** [comment]
I have manually changed the file as this is not released.

**Comment by neillturner** [comment]
well test the puppet. just create a new test server that calls puppet aws_scheduler module after updating the librarian puppet file and deleting the librarian puppet lock file.

**Comment by Dharmender-Singh** [comment]
ERROR:boto:401 Unauthorized
ERROR:boto:<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>Authorization header or parameters are not formatted correctly.</Message></Error></Errors><RequestID>*********</RequestID></Response>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file aws-scheduler.py, line 133
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file aws-scheduler.py, line 133

Also, I can't see the "If else" condition after running the puppet.

**Comment by neillturner** [comment]
the if else in the aws-scheduler.py script that is created? 
are you running the puppet script from from the github klink and version 0.0.7
doers librarian-puppet correctly resolve it?

**Comment by Dharmender-Singh** [comment]
[root@uuu]# /usr/bin/python /usr/sbin/aws-scheduler.py check
  File "/usr/sbin/aws-scheduler.py", line 51
    else:
        ^
IndentationError: unindent does not match any outer indentation level

**Comment by neillturner** [comment]
ok fixed that so test again -)

**Comment by Dharmender-Singh** [comment]
After running puppet again :--

Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file aws-scheduler.py, line 137
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/**init**.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/**init**.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file aws-scheduler.py, line 137

**Comment by neillturner** [comment]
I have made some changes to get default values for the keys of empty string. Hopefully it will work now. 

If not then take the try: and exception: out of aws-scheduler.py around line 127 then we can see what where the error is

**Comment by Dharmender-Singh** [comment]
Different Error this time :---

 File "/usr/sbin/aws-scheduler.py", line 55
    def get_with_default(section,name,default)
                                             ^
SyntaxError: invalid syntax

**Comment by neillturner** [comment]
Made come correction and did some testing so it should be close now. try testing again.

**Comment by Dharmender-Singh** [comment]
It's working now. Thanks :)

**Comment by neillturner** [comment]
This is now avaliable on the puppetforge as 
neillturner/aws_scheduler
version 0.0.7
